In [6]:
import pandas as pd
import numpy as np
import re

In [4]:
twitter_df = pd.read_csv("./data/twitter_content.csv", index_col=0)
twitter_df

,Datetime,Tweet Id,Text,Username,Location,FollowersCount,ReplyCount,RetweetCount
0,2021-09-03 23:59:59+00:00,1433942885716615173,"@POTUS flying entourage over W Jeff Parish, su...",AnthonyMcAuley2,World,443,0,0
1,2021-09-03 23:59:19+00:00,1433942716996485123,"Air operations underway @ Grand Isle, LA #Hurr...",ClarkCountyNV,"Las Vegas, Nevada",217434,0,1
2,2021-09-03 23:58:58+00:00,1433942626944884738,I signed up to volunteer by helping man the co...,dikayodata,‚öúÔ∏èüõ´‚õ©,6175,0,0
3,2021-09-03 23:58:16+00:00,1433942451937501191,New York AG suggests emergency housing for bas...,SputnikInt,NaN,325001,1,3
4,2021-09-03 23:57:08+00:00,1433942167152697346,Dammit bobby!\n#HurricaneIda https://t.co/6ljX...,NoTangledKnots,NaN,178,0,0
...,...,...,...,...,...,...,...,...
65529,2021-08-26 14:54:38+00:00,1430906539494154244,It's on! First official advisory on what is li...,ChuckBell4,"Washington, DC",32367,0,1
65530,2021-08-26 14:47:45+00:00,1430904806038642696,@ezrocks0011 @mal1976retaf @Lisaisback21 @fric...,enufs_enuf,Nunya TX,1228,1,2
65531,2021-08-26 13:28:18+00:00,1430884811292487682,Sorry not sorry.\n\n#Louisiana #SWLA #LakeChar...,unclejeet,NaN,788,0,1
65532,2021-08-26 13:01:08+00:00,1430877976632061961,Tomorrow will be the 1 year anniversary of #Hu...,EJ_Reine,"Louisiana, USA",4570,0,0
65533,2021-08-26 12:30:08+00:00,1430870173876211714,Un syst√®me tropical se renforce et se dirige v...,NewNiveau,"La Nouvelle Orl√©ans, Louisiane",427,1,2

## Split Date and Time

In [5]:
twitter_df['Dates'] = pd.to_datetime(twitter_df['Datetime']).dt.date
twitter_df['Time'] = pd.to_datetime(twitter_df['Datetime']).dt.time
twitter_df

,Datetime,Tweet Id,Text,Username,Location,FollowersCount,ReplyCount,RetweetCount,Dates,Time
0,2021-09-03 23:59:59+00:00,1433942885716615173,"@POTUS flying entourage over W Jeff Parish, su...",AnthonyMcAuley2,World,443,0,0,2021-09-03,23:59:59
1,2021-09-03 23:59:19+00:00,1433942716996485123,"Air operations underway @ Grand Isle, LA #Hurr...",ClarkCountyNV,"Las Vegas, Nevada",217434,0,1,2021-09-03,23:59:19
2,2021-09-03 23:58:58+00:00,1433942626944884738,I signed up to volunteer by helping man the co...,dikayodata,‚öúÔ∏èüõ´‚õ©,6175,0,0,2021-09-03,23:58:58
3,2021-09-03 23:58:16+00:00,1433942451937501191,New York AG suggests emergency housing for bas...,SputnikInt,NaN,325001,1,3,2021-09-03,23:58:16
4,2021-09-03 23:57:08+00:00,1433942167152697346,Dammit bobby!\n#HurricaneIda https://t.co/6ljX...,NoTangledKnots,NaN,178,0,0,2021-09-03,23:57:08
...,...,...,...,...,...,...,...,...,...,...
65529,2021-08-26 14:54:38+00:00,1430906539494154244,It's on! First official advisory on what is li...,ChuckBell4,"Washington, DC",32367,0,1,2021-08-26,14:54:38
65530,2021-08-26 14:47:45+00:00,1430904806038642696,@ezrocks0011 @mal1976retaf @Lisaisback21 @fric...,enufs_enuf,Nunya TX,1228,1,2,2021-08-26,14:47:45
65531,2021-08-26 13:28:18+00:00,1430884811292487682,Sorry not sorry.\n\n#Louisiana #SWLA #LakeChar...,unclejeet,NaN,788,0,1,2021-08-26,13:28:18
65532,2021-08-26 13:01:08+00:00,1430877976632061961,Tomorrow will be the 1 year anniversary of #Hu...,EJ_Reine,"Louisiana, USA",4570,0,0,2021-08-26,13:01:08
65533,2021-08-26 12:30:08+00:00,1430870173876211714,Un syst√®me tropical se renforce et se dirige v...,NewNiveau,"La Nouvelle Orl√©ans, Louisiane",427,1,2,2021-08-26,12:30:08

## Remove URL, mentions, hashtags, numbers and foreign languages from Tweets

In [45]:
twitter_df['CleanText'] = twitter_df['Text'].replace(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', '', regex=True)
twitter_df['CleanText'] = twitter_df['CleanText'].replace(r'@[A-Za-z0-9_]+', '', regex=True)
twitter_df['CleanText'] = twitter_df['CleanText'].replace(r'#[A-Za-z0-9_]+', '', regex=True)
twitter_df = twitter_df[twitter_df.CleanText.map(lambda x: x.isascii())]

In [47]:
twitter_df.to_csv("./data/cleaned_twitter.csv")